---
- name: Configure workstation
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars:
    ansible_become_exe: /usr/bin/sudo.ws # Workaround Ubuntu
  roles:
    - gnomerice
  tasks:
    - name: Ensure needed package are installed
      ansible.builtin.apt:
        name:
          - git
          - curl
          - vim
        state: present
