---
flatpak_packages:
  - name: org.keepassxc.KeePassXC
    state: present
  - name: com.github.IsmaelMartinez.teams_for_linux
    state: present
  - name: com.obsproject.Studio 
    state: present
  - name: com.logseq.Logseq
    state: present
