---
system_packages:
  - git
  - vim
  - curl
  - kitty # Terminal
  - flatpak
  - remmina
  - remmina-plugin-rdp
  - openvpn
  - direnv
  - starship
  - podman
  - gnome-shell
  - gnome-shell-extension-manager
  - gnome-shell-extensions
