---
# tasks file for roles/flatpak
- name: "Add the flathub flatpak repository remote to the user installation"
  community.general.flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    method: "user"
    state: "{{ flatpak_flathub_repo_enabled }}"
  tags:
    - "flatpak"
    - "flatpakrepo"

- name: "Install flatpak packages"
  community.general.flatpak:
    name: "{{ item.name }}"
    method: "user"
    state: "{{ item.state }}"
  loop: "{{ flatpak_packages }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - "flatpak"
    - "flatpakpackages"
