---
# tasks file for roles/gnome-rice
- name: Manage gnome overrides
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gnome_settings_overrides | dict2items }}"
